### PR TITLE
Adding damage model to 707.

### PR DESCRIPTION
**Pull request by l0k1**
This'll add the damage model that Op Red Flag uses in its plane and events.

### CODE REVIEW

**Comment by onox** [comment]
You can define this:

```javascript
var fail_systems = func (probability) {
    var failure_modes = FailureMgr._failmgr.failure_modes;
    var mode_list = keys(failure_modes);
    var failed = 0;
    foreach(var failure_mode_id; mode_list) {
        if (rand() < probability) {
            FailureMgr.set_failure_level(failure_mode_id, 1);
            failed += 1;
        }
    }
    return failed;
};
```

And then call it like this:

```javascript
var failed = fail_systems(probability);
```

**Comment by onox** [comment]
```javascript
var warhead_lbs = {
    "aim-120":              44.0,
    "AIM120":               44.0,
    "RB-99":                44.0,
    "aim-7":                88.0,
    "RB-71":                88.0,
    "aim-9":                20.8,
    "RB-24J":               20.8,
    "RB-74":                20.8,
    "R74":                  16.0,
    "MATRA-R530":           55.0,
    "Meteor":               55.0,
    "AIM-54":               135.0,
    "Matra R550 Magic 2":   27.0,
    "Matra MICA":           30.0,
};
```

Call it like this:

```javascript
var maxDist = maxDamageDistFromWarhead(warhead_lbs[type]);
```

**Comment by NikolaiVChr** [comment]
Cool.

It can be that the type is not in the hash though, so:

```
              var maxDist = 0;

              if (contains(warhead_lbs, type)) {
                maxDist = maxDamageDistFromWarhead(warhead_lbs[type]);
              } else {
                return;
              }
```

**Comment by l0k1** [comment]
Closing this for now, will do another pull request later.

**Pull request closed without merging**
