### PR TITLE
Updating 707

### PR DESCRIPTION
**Pull request by l0k1**
Hey,
This is just a conglomeration of other people's contributions that they've given to me:
-an updated damage.nas by Leto/Necolatis (modified so the 707 will take damage from farther away than a fighter, as it is a bigger plane than a fighter)
-the radar code by 5H1N0B1 (Mirage 2000 maintainer); this will hide planes on the radar if they are hiding behind terrain, and also if the plane is notching.

### CODE REVIEW

**Comment by onox** [comment]
I have only one comment this time: I see a lot of `settimer()` calls, but that function is kinda ugly and old. You better use `maketimer()`. For example, in `damage.nas` you remove the `settimer()` calls that start/continue `processCallsigns`. After that you do:

```javascript
var callsign_timer = maketimer(1.5, processCallsigns);
callsign_timer.start();
```

This way you decouple the logic of the function from the timer management (with `settimer()` you have to manually keep calling that function).

`maketimer()` also has a nice `.isRunning` property and a `stop()` and `restart()` function. See http://wiki.flightgear.org/Nasal_library#maketimer.28.29

Sorry for being a pain in the ass, but you better learn this now than in the future :wink: 

I see the same in `radar2.nas`, but it is okay for now if you just modify `damage.nas`.  Also, in general, if you have systems that loop and you want to enable/disable such systems during run-time, you might want to use `updateloop`. It handles all those FG signals, so resets and teleportation should not be a problem. See https://github.com/Juanvvc/c172p-detailed/blob/master/Nasal/tiedowns.nas for an example. (You might want to show this to 5H1N0B1 if he wrote `radar2.nas`)

**Comment by l0k1** [comment]
Calling @NikolaiVChr, for more damage.nas advice.

**Comment by NikolaiVChr** [comment]
The settimer calls in damage is used to be compatible with older FG versions. I guess same is true for Shinobis radar. Maketimer is only for newer FGs.

**Comment by onox** [comment]
@NikolaiVChr `maketimer()` is part of FG since 2.12. That version was released 2.5 years ago. I don't think anyone is still using <= 2.10 nowadays.

**Comment by NikolaiVChr** [comment]
Well the code comes from the Viggen, and I am keeping that compatible backwards till 2.10/2.8.

**Pull request merged**
